version: "3"

services:

  mysql-express:
    image: mysql:8.0.31
    container_name: mysql-express
    environment:
      MYSQL_ROOT_PASSWORD: express123
      MYSQL_DATABASE: express
      MYSQL_USER: express
      MYSQL_PASSWORD: express123
    ports:
      - "3981:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis-express:
    image: redis:latest
    container_name: redis-express
    environment:
      REDIS_PASSWORD: express123
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
    ports:
      - "6124:6379"

volumes:
  mysql_data: